### PR TITLE
Add German translation. Fixes #11

### LINKED ISSUE #11: Translate meta information
Looking at the present translations I noticed that `<title>` and `<meta name="description">` weren't translated. On purpose?

### PR DESCRIPTION
**Pull request by Ryuno-Ki**

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
Since I have no Facebook account someone else would need to provide the images.

**Comment by shahbaz17** [comment]
I see the logo.png in PT-BR also the display demo pic.
Is there any fix to it ?

**Comment by shahbaz17** [comment]
German translation or GET SMART ON PRIVACY is ?
And what i see is in PT-BR 
can you see this @Ryuno-Ki ?

**Comment by Ryuno-Ki** [comment]
_Get smart on privacy_ translates to _Informieren Sie sich über Privatsphäre_ (formal).
At least if I stick on how it was translated on https://www.mozilla.org/en-US/teach/smarton/

I saw it is used in `og:title` and meta description. Shall I translate those?

**Comment by shahbaz17** [comment]
But i don't find " Informieren Sie sich über Privatsphäre  " on the profile layout as well as in the logo.png
So are you not replacing these files ?

**Comment by Ryuno-Ki** [comment]
I've opened #11 because I was unsure. The Italian translation did not translate them as well.

logo.png is a PNG. Do we have the source file (say, a GIMP .xcf file) around? How shall I edit it?

**Comment by shahbaz17** [comment]
Hi @Ryuno-Ki i'm giving you the write access.
Since i don't have time all the time so it will be better to give admin access to you.
And you are doing a superb job.
And will definitely try to work on the issues.

**Comment by shahbaz17** [comment]
Can you resolve this conflict ?
And after resolving feel free to merge it.
I have invited you for the collaboration , do check your mail for it

**Comment by shahbaz17** [comment]
Its not working as desired. Can you have a look at http://privacymonth2017.online/DE-DE/
DE is before EN on index page
EN EN is there on DE page
Also On DE page logo.png is not showing

**Comment by shahbaz17** [comment]
All done.
No need to change.
Meanwhile go for other fixes

**Pull request merged**
