### PR TITLE
Few fix for IT

### PR DESCRIPTION
**Pull request by Mte90**

### CODE REVIEW

**Comment by shahbaz17** [comment]
Can you remove the daniele.png from your PR since i already updated it

**Comment by shahbaz17** [comment]
Updated the fix . Can you check the website http://privacymonth2017.online/ITA/

**Comment by Mte90** [comment]
so this pr is useless :-)

**Comment by shahbaz17** [comment]
Just re-check the fix . If any update needed do a PR :-)

**Pull request closed without merging**
