### PR TITLE
Add pt-BR language

### PR DESCRIPTION
**Pull request by cpswsg**

### CODE REVIEW

**Comment by cpswsg** [comment]
Fix #3

**Comment by shahbaz17** [comment]
Thanks @cynthiapereira for the PR.
Won't be able to merge this because its live here http://privacymonth2017.online/PT-BR/
Also we are working on to translate the overlay image as well.

**Comment by cpswsg** [comment]
Hey @shahbaz17.
It's necessary to make corrections in current translation and this PR fix this problems.

**Comment by shahbaz17** [comment]
Oh sorry , I received the text from Geraldo.
So can you use the updated codes since i have updated the overlay image text.
Use a fresh branch for new PR

**Pull request closed without merging**
