### PR TITLE
update pt-BR

### PR DESCRIPTION
**Pull request by cpswsg**

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
Since you add a .gitignore, you may want to check out https://www.gitignore.io/

**Comment by shahbaz17** [comment]
Won't be able to merge this since reviewer says the current running version is perfect.
Can you contact https://github.com/barrosgeraldo to discuss the things ?

**Comment by shahbaz17** [comment]
Any update @cynthiapereira @barrosgeraldo on this ?

**Comment by barrosgg** [comment]
The translation is up and running, there are no things to do here.

**Comment by barrosgg** [comment]
Please, approve this.

**Pull request merged**
