### PR TITLE
Update IT

### PR DESCRIPTION
**Pull request by edovio**
Changed the logo.png with the correct translation and HQ graphics

### CODE REVIEW

**Comment by shahbaz17** [comment]
Thanks @edovio for the HQ logo.
Just need to confirm the translated text.
Meanwhile can you contact https://github.com/Mte90 to verify the translation text

**Comment by Mte90** [comment]
yep it's okay we already discussed about that changes :-)

**Comment by shahbaz17** [comment]
All set to merge ?

**Comment by Mte90** [comment]
yep

**Pull request merged**
